export const definitions = [
  {
    key: 'Account',
    details: 'means a unique account created for You to access our Service or parts of our Service',
  },
  {
    key: 'Company',
    details: '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Forbole Limited, Flat 3B, Tontex Industrial Building, 2-4 Sheung Hei Street, San Po Kong, Kowloon',
  },
  {
    key: 'Cookies',
    details: 'are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses',
  },
  {
    key: 'Country',
    details: 'refers to: Hong Kong SAR China',
  },
  {
    key: 'Device',
    details: 'means any device that can access the Service such as a computer, a cellphone or a digital tablet',
  },
  {
    key: 'Personal Data',
    details: 'is any information that relates to an identified or identifiable individual',
  },
  {
    key: 'Service',
    details: 'refers to the Website',
  },
  {
    key: 'Service Provider',
    details: 'means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used',
  },
  {
    key: 'Third-party Social Media Service',
    details: 'refers to any website or any social network website through which a User can log in or create an account to use the Service',
  },
  {
    key: 'Usage Data',
    details: 'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)',
  },
  {
    key: 'Website',
    details: 'refers to Big Dipper, accessible from ',
  },
  {
    key: 'You',
    details: 'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable',
  },
];

export const trackingDefinitions = [
  {
    key: 'Cookies or Browser Cookies - ',
    details: 'A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies',
  },
  {
    key: 'Flash Cookies - ',
    details: 'Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read "Where can I change the settings for disabling, or deleting local shared objects?" available at https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_',
  },
  {
    key: 'Web Beacons - ',
    details: 'Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity)',
  },
];

export const cookies = [
  {
    key: 'Necessary / Essential Cookies',
    type: 'Session Cookies',
    administered: 'Us',
    purpose: 'These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services',
  },
  {
    key: 'Cookies Policy / Notice Acceptance Cookies',
    type: 'Persistent Cookies',
    administered: 'Us',
    purpose: 'These Cookies identify if users have accepted the use of cookies on the Website',
  },
  {
    key: 'Functionality Cookies',
    type: 'Persistent Cookies',
    administered: 'Us',
    purpose: 'These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website',
  },
  {
    key: 'Tracking and Performance Cookies',
    type: 'Persistent Cookies',
    administered: 'Third-Parties',
    purpose: 'These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new pages, features or new functionality of the Website to see how our users react to them',
  },
];
