/* eslint-disable max-len */
export const definitions = [
  {
    details:
      "means a unique account created for You to access our Service or parts of our Service",
    key: "Account",
  },
  {
    details:
      '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Forbole Limited, Flat 3B, Tontex Industrial Building, 2-4 Sheung Hei Street, San Po Kong, Kowloon',
    key: "Company",
  },
  {
    details:
      "are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses",
    key: "Cookies",
  },
  {
    details: "refers to: Hong Kong SAR China",
    key: "Country",
  },
  {
    details:
      "means any device that can access the Service such as a computer, a cellphone or a digital tablet",
    key: "Device",
  },
  {
    details:
      "is any information that relates to an identified or identifiable individual",
    key: "Personal Data",
  },
  {
    details: "refers to the Website",
    key: "Service",
  },
  {
    details:
      "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used",
    key: "Service Provider",
  },
  {
    details:
      "refers to any website or any social network website through which a User can log in or create an account to use the Service",
    key: "Third-party Social Media Service",
  },
  {
    details:
      "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)",
    key: "Usage Data",
  },
  {
    details: "refers to Big Dipper, accessible from ",
    key: "Website",
  },
  {
    details:
      "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable",
    key: "You",
  },
];

export const trackingDefinitions = [
  {
    details:
      "A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies",
    key: "Cookies or Browser Cookies - ",
  },
  {
    details:
      'Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read "Where can I change the settings for disabling, or deleting local shared objects?" available at ',
    key: "Flash Cookies - ",
  },
  {
    details:
      "Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity)",
    key: "Web Beacons - ",
  },
];

export const cookies = [
  {
    administered: "Us",
    key: "Necessary / Essential Cookies",
    purpose:
      "These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services",
    type: "Session Cookies",
  },
  {
    administered: "Us",
    key: "Cookies Policy / Notice Acceptance Cookies",
    purpose:
      "These Cookies identify if users have accepted the use of cookies on the Website",
    type: "Persistent Cookies",
  },
  {
    administered: "Us",
    key: "Functionality Cookies",
    purpose:
      "These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website",
    type: "Persistent Cookies",
  },
  {
    administered: "Third-Parties",
    key: "Tracking and Performance Cookies",
    purpose:
      "These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new pages, features or new functionality of the Website to see how our users react to them",
    type: "Persistent Cookies",
  },
];

export const dataUse = [
  {
    details: "including to monitor the usage of our Service",
    key: "To provide and maintain our Service - ",
  },
  {
    details:
      "to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user",
    key: "To manage Your Account - ",
  },
  {
    details:
      "the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service",
    key: "For the performance of a contract - ",
  },
  {
    details:
      "To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation",
    key: "To contact You - ",
  },
  {
    details:
      "with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information",
    key: "To provide You - ",
  },
  {
    details: "To attend and manage Your requests to Us",
    key: "To manage Your requests - ",
  },
  {
    details:
      "We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred",
    key: "For business transfers - ",
  },
  {
    details:
      "We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience",
    key: "For other purposes - ",
  },
];

export const dataUseTwo = [
  {
    details:
      "We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You",
    key: "With Service Providers - ",
  },
  {
    details:
      "We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company",
    key: "For business transfers - ",
  },
  {
    details:
      "We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us",
    key: "With Affiliates - ",
  },
  {
    details:
      "We may share Your information with Our business partners to offer You certain products, services or promotions",
    key: "With business partners - ",
  },
  {
    details:
      "when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile",
    key: "With other users - ",
  },
  {
    details:
      "We may disclose Your personal information for any other purpose with Your consent",
    key: "With Your consent - ",
  },
];

export const legalRequirements = [
  "Comply with a legal obligation",
  "Protect and defend the rights or property of the Company",
  "Prevent or investigate possible wrongdoing in connection with the Service",
  "Protect the personal safety of Users of the Service or the public",
  "Protect against legal liability",
];

export const analytics = [
  {
    details:
      "Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.\n\nYou can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.\n\nFor more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: ",
    key: "Google Analytics",
  },
  {
    details:
      "Matomo is a web analytics service. You can visit their Privacy Policy page here: ",
    key: "Matomo",
  },
];
